Installable comfy
comfyanonymous/ComfyUI pull request #1834
Opened 2023-10-25 12:00 UTC by XmYx

First step to make comfy a pip installable, importable package.
From here, in any env, that has comfyui pip installed (even via pip install git+https://www.github.com/XmYx/ComfyUI.git),
will be able to both run comfyui with a comfyui command (will need further adjustment to make sure model folders are as desired, since then comfyui lives in the env's lib/site-packages folder).
Additionally, any python project can import comfy functions and classes as simple as (from comfy.comfy.model_management import...). This could pave the way to create the most efficient and versatile sd sampling engine so far.

2023-10-27 18:04 UTC, CapsAdmin commented
My immediate reaction is that pytorch should be checked at runtime instead of force installing the cuda version.

If this was merged and I were to use comfy as a pip package, but I want to use the rocm version of pytorch, how should I go about doing that?

2023-10-27 22:12 UTC, XmYx commented
Of course. It's fairly straightforward, in our setup.py we just setup a lookup table, and add the package lists as dict elements as here:
https://github.com/huggingface/diffusers/blob/main/setup.py
This allows pip install comfyui to do a minimal dependency install, and opens the way for any other option, like:
pip install comfyui[torch], [rocm], [directml], [docker-trt], we just have to declare each list. I have a way to deal with specific versions if we use a table like that.

2023-12-01 12:52 UTC, akx requested changes
`*.egg-info` should never be committed.

2023-12-03 10:45 UTC, albertaillet commented on comfyui.egg-info/PKG-INFO
as previously mentined by [akx](https://github.com/akx) none of the files in this directory should be commited

2023-12-03 10:48 UTC, albertaillet commented on main.py
> +# if __name__ == "__main__":
this should probably not be commented out

2023-12-03 10:53 UTC, albertaillet commented on setup.py
> +torch_package_urls = {
this logic is probably not needed and/or the option of torch version to install could be given to the user.
examples of packages where only torch is added in the requirements and no other logic:
- [torchdynamo](https://github.com/pytorch/torchdynamo)
- [torchvision](https://github.com/pytorch/vision)
- [torchsde](https://github.com/google-research/torchsde)

2023-12-03 10:54 UTC, albertaillet commented on setup.py
> +            'comfyui=main:main',
documentation of how this entry point is used could be added

2023-12-03 10:57 UTC, albertaillet commented on setup.py
in general a more modern version using [pyproject.toml](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/) could be investigated

2023-12-04 04:00 UTC, doctorpangloss commented
you should probably look at https://github.com/comfyanonymous/ComfyUI/pull/298 and close this, since this PR has a lot of problems and is still at the beginning of the packaging journey

2024-03-09 19:07 UTC, closed without merging