Add terminal size fallback
comfyanonymous/ComfyUI pull request #5623
Opened 2024-11-15 04:52 UTC by yoland68

2024-11-15 20:51 UTC, huchenlei requested changes
Please specify context on why this change is needed.

2024-11-16 13:47 UTC, freakabcd commented
I'm a little bit confused by the diff. Why not just call `shutil.get_terminal_size()` within `update_size()`?

https://github.com/python/cpython/blob/main/Lib/shutil.py#L1438
seems to suggest that it handles all the cases and always returns a tuple (the fallback being `(80,24)`). 

Also would highly suggest usage of black (or ruff; just the formatter not the checker) on a project wide basis.

2024-11-16 15:36 UTC, yoland68 commented
> Please specify context on why this change is needed.

Added context

2024-11-17 00:17 UTC, huchenlei approved these changes

2024-11-18 18:02 UTC, huchenlei commented
@comfyanonymous Ping on review.

2024-11-19 08:34 UTC, merged